# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 193576e7522360952dd807ca876e4a301a74435244ccf7b1c46996c1a882948de67edfe797990c9815792f75b2e7a5c8fa28d5a0564b821d0a0ac54faee926bf

test:
  secret_key_base: 8e3d0630a58486116dc3da229e449423059c2fb11098212ba7227f7d3eb92bec3756b3930dae856c548e1fcce28cc1f74c8975eb08445213648851988fa9f99d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
